---

- name: Generate startup.options file
  template:
    src: etc/logstash/startup.options.j2
    dest: "{{ logstash_settings_dir }}startup.options"
    owner: root
    group: root
    mode: 0644
  notify:
   - setup logstash service
   - reenable logstash.service
   - restart logstash

- name: Generate jvm.options file
  template:
    src: etc/logstash/jvm.options.j2
    dest: "{{ logstash_settings_dir }}jvm.options"
    owner: root
    group: root
    mode: 0644
  notify:
   - restart logstash

- name: Copy Logstash Configuration
  template:
    src: etc/logstash/logstash.yml.j2
    dest: "{{ logstash_settings_dir }}logstash.yml"
    owner: root
    group: root
    mode: 0644
  notify:
   - restart logstash
