---

- name: Ensure Logstash Patterns Directory Exists
  file:
    path: "{{ logstash_patterns_file|dirname }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy Logstash Patterns Configuration
  template:
    src: patterns.j2
    dest: "{{ logstash_patterns_file }}"
    owner: root
    group: root
    mode: 0644
  notify:
   - restart logstash

- name: Validate and copy Logstash Input Configuration
  environment:
    LS_JVM_OPTS: "{{ logstash_jvm_options_path }}"
    LS_JAVA_OPTS: "{{ logstash_java_opts }}"
  template:
    src: input.conf.j2
    dest: "{{ logstash_conf_dir }}input.conf"
    owner: root
    group: root
    mode: 0644
    validate: "{{ logstash_config_validate_envs }} {{ logstash_home }}/bin/logstash {{ logstash_config_validate_params }}"
  notify:
   - restart logstash

- name: Validate and copy Logstash Filter Configuration
  environment:
    LS_JVM_OPTS: "{{ logstash_jvm_options_path }}"
    LS_JAVA_OPTS: "{{ logstash_java_opts }}"
  template:
    src: filters.conf.j2
    dest: "{{ logstash_conf_dir }}filters.conf"
    owner: root
    group: root
    mode: 0644
    validate: "{{ logstash_config_validate_envs }} {{ logstash_home }}/bin/logstash {{ logstash_config_validate_params }}"
  notify:
   - restart logstash

- name: Validate and copy Logstash Output Configuration
  environment:
    LS_JVM_OPTS: "{{ logstash_jvm_options_path }}"
    LS_JAVA_OPTS: "{{ logstash_java_opts }}"
  template:
    src: output.conf.j2
    dest: "{{ logstash_conf_dir }}output.conf"
    owner: root
    group: root
    mode: 0644
    validate: "{{ logstash_config_validate_envs }} {{ logstash_home }}/bin/logstash {{ logstash_config_validate_params }}"
  notify:
   - restart logstash
